# Generated by Django 2.1.7 on 2019-03-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postbin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
